/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.util.Enumeration;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import model.Medicamento;

/**
 *
 * @author Luís Gustavo
 */
public class FormCadastroMedicamento extends javax.swing.JFrame {

    /**
     * Creates new form FormCadastroMedicamento
     */
    public FormCadastroMedicamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbCodigoBarra = new javax.swing.JLabel();
        tfCodigoBarra = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbLaboratorio = new javax.swing.JLabel();
        tfLaboratorio = new javax.swing.JTextField();
        lbLocalizacao = new javax.swing.JLabel();
        cbLocalizacao = new javax.swing.JComboBox<>();
        lbValorUnitario = new javax.swing.JLabel();
        tfValorUnitario = new javax.swing.JTextField();
        lbComposicao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taComposicao = new javax.swing.JTextArea();
        lbQuantidadeEstoque = new javax.swing.JLabel();
        tfQuantidadeEstoque = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbAnsiolitico = new javax.swing.JRadioButton();
        rbAntibiotico = new javax.swing.JRadioButton();
        rbAnalgesico = new javax.swing.JRadioButton();
        rbHormonal = new javax.swing.JRadioButton();
        rbPolivitaminico = new javax.swing.JRadioButton();
        btInserir = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btVender = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Medicamento");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lbCodigoBarra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCodigoBarra.setText("Código de Barra:");
        lbCodigoBarra.setName("lbCodigoBarra"); // NOI18N

        tfCodigoBarra.setName("tfCodigoBarra"); // NOI18N

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNome.setText("Nome:");
        lbNome.setName("lbNome"); // NOI18N

        tfNome.setName("tfNome"); // NOI18N

        lbLaboratorio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbLaboratorio.setText("Laboratório:");
        lbLaboratorio.setName("lbLaboratorio"); // NOI18N

        tfLaboratorio.setName("tfLaboratorio"); // NOI18N

        lbLocalizacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbLocalizacao.setText("Localização:");
        lbLocalizacao.setName("lbLocalizacao"); // NOI18N

        cbLocalizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07" }));
        cbLocalizacao.setName("cbLocalizacao"); // NOI18N

        lbValorUnitario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbValorUnitario.setText("Valor Unitário:");
        lbValorUnitario.setName("lbValorUnitario"); // NOI18N

        tfValorUnitario.setText("0");
        tfValorUnitario.setName("tfValorUnitario"); // NOI18N
        tfValorUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfValorUnitarioKeyTyped(evt);
            }
        });

        lbComposicao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbComposicao.setText("Composição:");
        lbComposicao.setName("lbComposicao"); // NOI18N

        taComposicao.setColumns(20);
        taComposicao.setLineWrap(true);
        taComposicao.setRows(5);
        taComposicao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        taComposicao.setName("taComposicao"); // NOI18N
        jScrollPane1.setViewportView(taComposicao);

        lbQuantidadeEstoque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbQuantidadeEstoque.setText("Quantidade em Estoque:");
        lbQuantidadeEstoque.setName("lbQuantidadeEstoque"); // NOI18N

        tfQuantidadeEstoque.setText("0");
        tfQuantidadeEstoque.setName("tfQuantidadeEstoque"); // NOI18N
        tfQuantidadeEstoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQuantidadeEstoqueKeyTyped(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        bgTipo.add(rbAnsiolitico);
        rbAnsiolitico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbAnsiolitico.setSelected(true);
        rbAnsiolitico.setText("Ansiolítico");
        rbAnsiolitico.setName("rbAnsiolitico"); // NOI18N

        bgTipo.add(rbAntibiotico);
        rbAntibiotico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbAntibiotico.setText("Antibiótico");
        rbAntibiotico.setName("rbAntibiotico"); // NOI18N

        bgTipo.add(rbAnalgesico);
        rbAnalgesico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbAnalgesico.setText("Analgésico");
        rbAnalgesico.setName("rbAnalgesico"); // NOI18N

        bgTipo.add(rbHormonal);
        rbHormonal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbHormonal.setText("Hormonal");
        rbHormonal.setName("rbHormonal"); // NOI18N

        bgTipo.add(rbPolivitaminico);
        rbPolivitaminico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbPolivitaminico.setText("Polivitamínico");
        rbPolivitaminico.setName("rbPolivitaminico"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAnsiolitico)
                .addGap(18, 18, 18)
                .addComponent(rbAntibiotico)
                .addGap(18, 18, 18)
                .addComponent(rbAnalgesico)
                .addGap(10, 10, 10)
                .addComponent(rbHormonal)
                .addGap(18, 18, 18)
                .addComponent(rbPolivitaminico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAnsiolitico)
                    .addComponent(rbAntibiotico)
                    .addComponent(rbAnalgesico)
                    .addComponent(rbHormonal)
                    .addComponent(rbPolivitaminico))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btInserir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/inserir.png"))); // NOI18N
        btInserir.setText("Inserir");
        btInserir.setMaximumSize(new java.awt.Dimension(125, 57));
        btInserir.setName("btInserir"); // NOI18N
        btInserir.setPreferredSize(new java.awt.Dimension(125, 57));
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/buscar.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.setMaximumSize(new java.awt.Dimension(125, 57));
        btBuscar.setName("btBuscar"); // NOI18N
        btBuscar.setPreferredSize(new java.awt.Dimension(125, 57));
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setMaximumSize(new java.awt.Dimension(125, 57));
        btLimpar.setName("btLimpar"); // NOI18N
        btLimpar.setPreferredSize(new java.awt.Dimension(125, 57));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btVender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/vender.png"))); // NOI18N
        btVender.setText("Vender");
        btVender.setEnabled(false);
        btVender.setName("btVender"); // NOI18N
        btVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVenderActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setMaximumSize(new java.awt.Dimension(125, 57));
        btSair.setName("btSair"); // NOI18N
        btSair.setPreferredSize(new java.awt.Dimension(125, 57));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.setEnabled(false);
        btEditar.setMaximumSize(new java.awt.Dimension(125, 57));
        btEditar.setName("btEditar"); // NOI18N
        btEditar.setPreferredSize(new java.awt.Dimension(125, 57));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btVender))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCodigoBarra)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbValorUnitario))
                                    .addComponent(tfCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbComposicao)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbNome))))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbLaboratorio)
                                    .addComponent(tfLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbQuantidadeEstoque)
                                    .addComponent(tfQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbLocalizacao)
                                    .addComponent(cbLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoBarra)
                    .addComponent(lbNome)
                    .addComponent(lbLaboratorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorUnitario)
                    .addComponent(lbComposicao)
                    .addComponent(lbQuantidadeEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbLocalizacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVender)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(889, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        tfCodigoBarra.setText("");
        tfNome.setText("");
        tfLaboratorio.setText("");
        tfValorUnitario.setText("0");
        taComposicao.setText("");
        tfQuantidadeEstoque.setText("0");
        cbLocalizacao.setSelectedIndex(0);
        bgTipo.clearSelection();
        rbAnsiolitico.setSelected(true);
        tfCodigoBarra.requestFocus();
        btInserir.setEnabled(true);
        btVender.setEnabled(false);
        btEditar.setEnabled(false);
    }//GEN-LAST:event_btLimparActionPerformed

    private void tfValorUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorUnitarioKeyTyped
        String caracteres = "0987654321";
        if(!caracteres.contains(evt.getKeyChar() + "")){
            evt.consume();
        }
    }//GEN-LAST:event_tfValorUnitarioKeyTyped

    private void tfQuantidadeEstoqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantidadeEstoqueKeyTyped
        String caracteres = "0987654321";
        if(!caracteres.contains(evt.getKeyChar() + "")){
            evt.consume();
        }
    }//GEN-LAST:event_tfQuantidadeEstoqueKeyTyped

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        Medicamento medicamento = new Medicamento();
        medicamento.setCodigoBarra(tfCodigoBarra.getText());
        medicamento.setNome(tfNome.getText());
        medicamento.setLaboratorio(tfLaboratorio.getText());
        medicamento.setValorUnitario(Double.parseDouble(tfValorUnitario.getText()));
        medicamento.setComposicao(taComposicao.getText());
        medicamento.setQuantidadeEstoque(Integer.parseInt(tfQuantidadeEstoque.getText()));
        medicamento.setLocalizacao(cbLocalizacao.getSelectedItem().toString());
        JRadioButton radio;
        Enumeration jr = bgTipo.getElements(); 
        while ( jr.hasMoreElements() )
        {
            radio = (JRadioButton) jr.nextElement(); 
            if (radio.isSelected())
            {
                medicamento.setTipo(radio.getText());
            }
        }
        
        if(medicamento.validaMedicamento()){
            Medicamento med = FormPrincipal.bdMedicamento.buscaMedicamento(tfCodigoBarra.getText(), tfNome.getText());
            if(med != null){
                JOptionPane.showMessageDialog(null, "Já existe este medicamento cadastrado!", "Cadastro Existente", JOptionPane.ERROR_MESSAGE);
            }else{
                FormPrincipal.bdMedicamento.adicionaMedicamento(medicamento);
                JOptionPane.showMessageDialog(null, "Medicamento cadastrado com sucesso!", "Cadastro de Medicamento", JOptionPane.INFORMATION_MESSAGE);
                btInserir.setEnabled(false);
            }            
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Falta de Preenchimento", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btInserirActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        if((!tfCodigoBarra.getText().trim().equals("")) || (!tfNome.getText().trim().equals(""))){
            Medicamento medicamento = FormPrincipal.bdMedicamento.buscaMedicamento(tfCodigoBarra.getText(), tfNome.getText());
            if(medicamento != null){
                tfCodigoBarra.setText(medicamento.getCodigoBarra());
                tfNome.setText(medicamento.getNome());
                tfLaboratorio.setText(medicamento.getLaboratorio());
                tfValorUnitario.setText(Double.toString(medicamento.getValorUnitario()));
                taComposicao.setText(medicamento.getComposicao());
                tfQuantidadeEstoque.setText(Integer.toString(medicamento.getQuantidadeEstoque()));
                cbLocalizacao.setSelectedItem(medicamento.getLocalizacao());
                JRadioButton radio;
                Enumeration jr = bgTipo.getElements(); 
                while ( jr.hasMoreElements() ) { 
                    radio = (JRadioButton) jr.nextElement(); 
                    if (radio.getText().equals(medicamento.getTipo())) 
                        radio.setSelected(true); 
                }
                btVender.setEnabled(true);
                btEditar.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "Medicamento não encontrado!", "Pesquisa de Medicamento", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Preencha o código de barra ou nome para fazer a busca!", "Falta de Preenchimento", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVenderActionPerformed
        String recebe = JOptionPane.showInputDialog(null, "Informe a quantidade que será vendida!", "Quantidade de Venda", JOptionPane.YES_OPTION);
        Medicamento medicamento = FormPrincipal.bdMedicamento.buscaMedicamento(tfCodigoBarra.getText(), tfNome.getText());
        if(medicamento != null){
            boolean res = medicamento.locar(Integer.parseInt(recebe));
            if(res){
                JOptionPane.showMessageDialog(null, "Medicamento Vendido!\nO valor total da venda é R$ " + medicamento.calcularValorTotalVenda(Integer.parseInt(recebe)), "Venda de Medicamento", JOptionPane.INFORMATION_MESSAGE);
                tfQuantidadeEstoque.setText(Integer.toString(medicamento.getQuantidadeEstoque()));
            }
        }
    }//GEN-LAST:event_btVenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVender;
    private javax.swing.JComboBox<String> cbLocalizacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigoBarra;
    private javax.swing.JLabel lbComposicao;
    private javax.swing.JLabel lbLaboratorio;
    private javax.swing.JLabel lbLocalizacao;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbQuantidadeEstoque;
    private javax.swing.JLabel lbValorUnitario;
    private javax.swing.JRadioButton rbAnalgesico;
    private javax.swing.JRadioButton rbAnsiolitico;
    private javax.swing.JRadioButton rbAntibiotico;
    private javax.swing.JRadioButton rbHormonal;
    private javax.swing.JRadioButton rbPolivitaminico;
    private javax.swing.JTextArea taComposicao;
    private javax.swing.JTextField tfCodigoBarra;
    private javax.swing.JTextField tfLaboratorio;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfQuantidadeEstoque;
    private javax.swing.JTextField tfValorUnitario;
    // End of variables declaration//GEN-END:variables
}
